### PR TITLE
IT'S ALIVE (Added Utils.html and Utils.js)

### PR DESCRIPTION
**Pull request by thmsdnnr**
Kevin: I kind of forked your index and created Utils.html that includes your JS file, jQuery, and my new utils.js code, so your index.html remains untouched. If you want we can keep kinda working separate files like this until we merge if that works?

ALSO, all the stuff you have in your JSON data structure looks awesome and should totally be added. The JSON I have here is just the object that we'd put in like a "boardData" key or what have you of your JSON structure, which contains all the important board metadata and misc :)

We now should have something that can take any tsv formatted like this

and generate JSON like this:
```json
{
	"1A": {
		"word": "BOWS",
		"clue": "Yields",
		"dir": "H"
	},
...
	"15L": {
		"word": "EPEE",
		"clue": "Small sword",
		"dir": "H"
	}
}
```
an array like this: 

```javascript
[["B","O","W","S","~","R","E","T","I","P","~","I","C","O","N"],["E","R","I","E","~","A","C","O","T","E","~","S","H","U","E"],["T","A","K","E","~","S","H","U","C","K","~","L","E","S","S"],["A","L","I","N","K","T","O","T","H","E","P","A","S","T","~"],["~","~","~","~","L","E","E","~","~","D","U","N","T","S","~"],["S","K","Y","W","A","R","D","S","W","O","R","D","~","~","~"],["A","C","R","O","S","S","~","T","O","G","A","~","S","P","A"],["T","A","L","K","~","~","D","A","O","~","~","F","U","L","L"],["S","L","Y","~","A","P","E","S","~","I","T","A","L","I","A"],["~","~","~","T","H","E","W","I","N","D","W","A","K","E","R"],["~","F","R","E","O","N","~","~","E","O","E","~","~","~","~"],["~","L","I","N","K","S","A","W","A","K","E","N","I","N","G"],["W","O","T","D","~","A","C","O","R","N","~","O","N","I","R"],["A","S","H","E","~","V","I","D","E","O","~","M","E","N","U"],["T","S","A","R","~","E","V","E","R","T","~","E","P","E","E"]]
```

and a board like this (either empty or full, based on a flag) with naive input validation:

# Next Big Step:
[  ] Figure out how to generate something like the initial TSV from any given list of words and clues so we can feed it into the existing code. Then we have more or less solve the "create this board" problem.

# Next Small Steps:
[  ] General User-experience/back end, storing crosswords, different outputs, etc etc etc
[  ] Calculating clues (e.g., 1 Across, 14 Down) from codes like 1A for better output
[  ] Client-side obfuscation of "correct" answers: don't store in data-text but store somehow hashed with a secret in the client and compare or figure out how to work this out
[  ] Store state-management for the board (which letters user has entered, which letters are blank) to enable comparison with correct board solution on the back-end
[  ] Maybe implement in React for state management (addresses above)
[  ] More intelligent back-end letter validation: have a concept of a "word" so when the user changes the board state, we only check whole WORDS and display whether they're correct or not, rather than letter-by-letter

# Utils.js functions

## handleKeyDown(e)
Does some initial naive letter-by-letter validation of user input against data-text value. If input value matches data-text, paint cell green. If cell is erased, paint cell white. If cell has the wrong letter, paint cell red.

**NOTE:** I'm doing a .toUpperCase() to compare the entered keyboard value with the answer value. We might want to make all the letters uppercase by default on the input itself before it's passed to the script.

### given a div (dom selector), board (board from populateBoardArray) populates the board in the formatting you want for your beautiful CSS display.

If blank, outputs:
`<div class="cell cell--filled"></div>`

Otherwise, it calls into this function populatedCell(letter, x, y, printAnswer=true)
which outputs (if answer is false, the value="${letter}" is omitted, and the cell is initially blank:
```html
<div class="cell" data-text="${letter}" data-row="${x}" data-col="${y}"><input type="text" maxLength="1" class="cell--text" value="${letter}"/></div>
```

### returns the array indices at which to begin drawing a word.
e.g., "1F" -> (0, 6)

## populateBoardArray(board, wordPosDict) 
###returns a board populated with words from wordsPosDict

Initialize board with an array containing a tilde for all strings. Something like this:
```javascript
let size = 15;
  let board = [...Array(size).keys()].map(i => Array(size)); //generate empty size x size array
  for (var i=0;i<board.length;i++) { //this is ugly and probably better way to do it
    for (var j=0;j<board[i].length;j++) {
      board[i][j]='~'; //placeholder for empty cell
    }
  }
```

Call populateBoardArray on it with a wordPosDict calculated from tsvToJSON. The returned board will have tildes for blank spaces and the letters populated based on the ID indices — e.g., 1F ... Horizontal is translated into "start writing the WORD from the dictionary with key 1F at row 0, column 6, and fix the row, increment the columns (write horizontally)"

The output is something like this (ignore the strikethroughs: markdown formats tildes strangely).
```javascript
[["B","O","W","S","~","R","E","T","I","P","~","I","C","O","N"],["E","R","I","E","~","A","C","O","T","E","~","S","H","U","E"],["T","A","K","E","~","S","H","U","C","K","~","L","E","S","S"],["A","L","I","N","K","T","O","T","H","E","P","A","S","T","~"],["~","~","~","~","L","E","E","~","~","D","U","N","T","S","~"],["S","K","Y","W","A","R","D","S","W","O","R","D","~","~","~"],["A","C","R","O","S","S","~","T","O","G","A","~","S","P","A"],["T","A","L","K","~","~","D","A","O","~","~","F","U","L","L"],["S","L","Y","~","A","P","E","S","~","I","T","A","L","I","A"],["~","~","~","T","H","E","W","I","N","D","W","A","K","E","R"],["~","F","R","E","O","N","~","~","E","O","E","~","~","~","~"],["~","L","I","N","K","S","A","W","A","K","E","N","I","N","G"],["W","O","T","D","~","A","C","O","R","N","~","O","N","I","R"],["A","S","H","E","~","V","I","D","E","O","~","M","E","N","U"],["T","S","A","R","~","E","V","E","R","T","~","E","P","E","E"]]
```

### given a tab-delimited value file in this format:

**|ID|Word |Clue|Direction (horiz/vertical)**
1F	RETIP	Fix a broken cue stick, perhaps	H

generates an object that looks like this:
```json
{
	"1A": {
		"word": "BOWS",
		"clue": "Yields",
		"dir": "H"
	},
...
	"15L": {
		"word": "EPEE",
		"clue": "Small sword",
		"dir": "H"
	}
}
```

### CODE REVIEW

**Comment by kbrtrm** [comment]
!

**Comment by kbrtrm** [comment]
> Figure out how to generate something like the initial TSV from any given list of words and clues so we can feed it into the existing code. Then we have more or less solve the "create this board" problem

How is the given list of words formatted? How is the list received/consumed?

Also, it seems like this is where H/V across/down gets super gnarly! No? Are we heavily relying on the list provider's input to do most of the leg work or is it more of a seed (i.e. here are my big theme clues, help me craft the filler)?

**Comment by thmsdnnr** [comment]
For sure. I was thinking about this more last night. Maybe it's a thing we
can table until we get slightly further down the road? We can tack on a lot
of other features and UI stuff as long as the whole 2D array for the board
data structure makes sense, and then we can alter the tab delimited text
format if we choose. It's pretty easy to parse that stuff and fees it into
our board. I was envisioning some interface where you give it a list of
words and clues that are stored intetnally as a TSV, sort of like a "board
builder mode" where you choose a dimension (#squares per row) and can then
start entering words and clues at the bottom. Maybe the UI can
automatically put in numbers for entered words and then we pop open little
input boxes or DIVs as the words are entered for clue input.

I dunno! By the way, a lot of this is me throwing out ideas that could be
totally wrong and misguided. So don't feel attached to any of these
approaches necessarily. Can totally rework as we see fit!

**Comment by thmsdnnr** [comment]
From some of the discussion here http://stackoverflow.com/questions/943113/algorithm-to-generate-a-crossword it seems like a method to try might be having the user input some words we definitely want to include in the crossword (along with user-provided clues) and then allowing a dictionary search for filler words and pre-written clues. 

It also sounds like there's a sparse and a dense algorithm: dense being you provide the algorithm with dimension constraints (15x15) and a list of the black squares, and then it finds words to match the board. Sparse being you provide it with words and it just creates a board, trying to maximize crossings of words, but there's no guarantee it'll fit a certain geometry or look pretty.

It seems like the editing tool should be something that helps the end user with finding similar words + providing optional clues and making them editable. E.G., there's a space for a word I haven't supplied that will fit the word "YELLOW", so when the user's filling it in, they can click a box to get a list of suggested words/clues. If they select one, we prepopulate the clue we have on our end, but they can customize it. In this way, even if every WORD is not user supplied, every either word or clue can be user-supplied, which is pretty customizable.

**Comment by kbrtrm** [comment]
> user input some words ... and then allowing a dictionary search for filler words and pre-written clues

Yes, exactly! And pre-written clues could easily just be a standard definition (it's up to user to rewrite it as an interesting clue)

All of those threads seem to be beating around the dense, NYT-style bush—you know? One response even says it can't make dense crosswords. What are we missing? I think we can do it!

We're on the same page for the editing tool. Love the idea that it can not only find possible fills but can also be a sort of xw butler, helping you find other word options, letting you know the potential difficulty/rarity of a word, how a change affects the rest of the board, etc.

**Pull request merged**
