### PR TITLE
adding react, code modularization, webpack

### PR DESCRIPTION
**Pull request by thmsdnnr**
# true story ^ 

So the board route now renders a React component & I have it running on Heroku. We don't need the kludgey setTimeout hack in your index thing anymore because my script doesn't use the `window.onload=function(){}` anymore. I removed your setTimeout and things still seem to work ok.

## I also tried to set up Webpack.
If you change anything in the /client/app folder or the /lib/ folder, you can rebuild the bundle like this (let me know if this breaks or not for you):

1) reinstall with **npm install**, since I added a few dev dependencies to transpile ES6
and then 
2) **npm run build** from the root directory. If this doesn't break, npm run build should call Webpack which transpiles ES6 to ES5 and includes the /lib/board and /lib/timer files. 

It creates the "bundle.js" file which gets dropped into /static/assets/js automatically, and which test.ejs includes near the footer.

In a perfect world we can configure webpack to bundle **all** the vendor plugins (so the React and jQuery files) PLUS all our stuff, so the library function modules, your UI code, my back-end code, so it's all one minified JS file that loads in order, so we don't have any of that setTimeout weirdness. This might be a bit too optimistic but it could work!

## refactoring and misc
I'm trying to break out some of these common functions into libraries, so we can reuse and write tests for them. For instance, when we write the "editor" component, we can just include /lib/board and have our "generate a blank array" function or our "generate HTML given this array" functions in one place.

Along the way I discovered a bunch of kludgey code that I tried to refactor. I tried doing this thing called "Isomorphic React" where you write the same code to run on the client and the server, and the server renders the "skeleton" to the browser, and then when the browser loads, it "picks up/hooks onto" this React element somehow. The idea was that it was better for SEO / performant page loads, but in hindsight it was like I was trying using a sledgehammer to butter a slice of toast. It was very painful, so I abandoned it.

## Can we plan some "workflows" through editing mode, so like what the board should look like when you first enter "Edit Mode", what interactions look like, etc.?
I know some of the features that we want, but I'm wondering how they kind of flow instead of duct-taping things together

## My current goals:
[  ] Clean up code a bit more: there's a lot of logic in the event listener on the board component
[  ] Put your clue generation function into the board library and maybe render clues as a separate child component of a parent Board Container component? Not sure if it's worth it. It works now, but the DOM manipulation is a side-effect of calling the function, rather than something we're having React render. This might not matter though.

Data model stuff:
[   ] Tie board creation to the logged-in user

edit mode stuff?
[  ] Get started writing some of the UI stuff for designing a board?
[   ] When you're in the word, highlight the cells corresponding to that word
[   ] Have option (like a button) to "seek suggestions" for the current word
[   ] toggleable "mirror-mode" from shift-click drawing the black squares (so like, reflect about the diagonal)
[   ] see the suggestions overlaid in the board somehow (populate cells with lower opacity or something)
[   ] Better way of entering clues in real-time so you don't have to wait until you've decided on the whole board to decide on clues

pet feature
[   ] Sobel image filtering on crossword images to count the number of cells so you can drag-and-drop an image of a crossword puzzle and, at the least, copy the dimensions and black squares so you can import a board of this "design" into the project

### CODE REVIEW

**Comment by kbrtrm** [comment]
Trying to test this out... first error was that I didn't have babel-core, so I installed that. Now when I try to run `npm run build` I'm getting a SyntaxError (?)

```
ERROR in ./client/app/board.jsx
Module build failed: SyntaxError: Unexpected token (99:16)

   97 |   render() {
   98 |         let board=renderBoardHTML(this.state.answer_board);
>  99 |         return (<div className={"board board-size-" + this.state.BOARDSIZE} id="board"
      |                 ^
  100 |         dangerouslySetInnerHTML={{__html: board}}></div>);
  101 |     }
  102 | }
````

**Comment by kbrtrm** [comment]
Also, we can support larger than 15, yep. And yes, edit mode flows for sure.

**Comment by thmsdnnr** [comment]
Hmm. Maybe try npm install --save-dev babel-cli

Let me know if that works, and I can put it back in the dev dependencies. I
removed some dependencies from package.json that I thought I ended up NOT
using, but I must have pulled something out that we need. These are the
original dev dependencies before I started pulling stuff:

  "devDependencies": {
    "babel-cli": "^6.23.0",
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0"

**Comment by thmsdnnr** [comment]
Huh, okay weird, I tried uninstalling babel-cli and that didn't create the
issue on my end. Can you send me what your package.json looks like so that
I can try to reproduce it?

**Comment by kbrtrm** [comment]
:)

**Comment by thmsdnnr** [comment]
OH MAN it had nothing to do with dependencies and (I'm pretty sure) everything to do with the fact that git didn't automatically add .babelrc as a tracked file because it starts with a period. Try pulling one more time to get the .babelrc

I added babel-core to the dev-dependencies on package.json too.

**Comment by kbrtrm** [comment]
There we go!

**Pull request merged**
