### PR TITLE
Added logic for across and down lists

### PR DESCRIPTION
**Pull request by kbrtrm**
Well, I have an across and down list generator working (for the most part). It fails if there are any sneaky invalid answers. I'll show you, here's where it's working:

screen shot 2017-02-19 at 1 51 31 pm
screen shot 2017-02-19 at 1 51 38 pm

And, not so much:

screen shot 2017-02-19 at 1 51 59 pm
screen shot 2017-02-19 at 1 52 05 pm

It gets thrown off by 12 there in the center. There's no clue/answer/data for what it thinks is a one-letter down clue there. I'm sure we can figure out a way to fix that.

The other thing I'm stumped on is why that (document).ready I moved to the end of index.js isn't firing on load? Sometimes it will run on refresh. Any ideas?

### CODE REVIEW

**Comment by thmsdnnr** [comment]
Sweet, I'll take a look at this now. On the React side of things, I'm still
working to figure it out. Might be another few days. I've been reaaaly
tired lately (maybe a little bit of the flu or something?) so that's not
helping. Not ignoring the project though :)

**Comment by thmsdnnr** [comment]
For the document ready, I wonder if it's because my script uses

window.onload = function() {

to wrap all the content, and I populate the board div in a for loop within
that. I read some people saying that $(document.ready) would fire before
all the CONTENT was present but when the DOM was ready. I don't know if the
content includes the innerHTML of the div that my code puts the board into.

Maybe you could test that hypothesis by calling the functions in your
document.ready function after one second passes? Like a
setTimeout(function(){
//onload functions here
},1000);

**Comment by thmsdnnr** [comment]
When the react version gets going it should eliminate this sort of thing
because there's a "lifecycle method" for the board component that will call
whatever functions need to be called before and after it's "mounted" to the
DOM, so we can throw all our function calls into that and they should get
done in sync!

**Comment by kbrtrm** [comment]
New commit gets us started with a bootstrap base. 😀
Still a lot of work to do, but this gives us a little shape.

screen shot 2017-02-19 at 8 38 36 pm

**Comment by kbrtrm** [comment]
Oh! And I _did_ put my doc.ready scripts in a timeout function and it does indeed make a fine workaround for now!

**Review by thmsdnnr — APPROVED** [review]
This looks super great! Love the bootstrap styling so that the layout is now more responsive to match the responsiveness of the board itself.

**Pull request merged**
