### PR TITLE
PR #3, Heroku App Deployment

### PR DESCRIPTION
**Pull request by thmsdnnr**
# deployed version at https://worrd.herokuapp.com/ :heart_eyes_cat:
I recommend logging in with test/test and clicking "MY BOARDS". I created boards of every possible dimension from 1x1 to 15x15, which contains our original prototype board. You can also access that board directly by clicking here: https://worrd.herokuapp.com/b/Original%20Board

## This change adds a lot of code & we should probably discuss in the comments _before_ we merge. 

It's really just a sandbox to test data model stuff and server-side stuff before committing to a view framework and making some other decisions. I'm not sure of the best way for us to share stuff posted there. I can pull any of your work and then push and deploy it to Heroku. We can set up automatic deploys based off a Github repo, but I don't know how that works with a shared repository. Anyway, it moves a lot of the client only code to server-side code, or code that's rendered in an EJS view http://www.embeddedjs.com/

#### Broadly:

MongoDB -> Mongoose -> Node JS -> Express -> EJS views ->  end user

App Routes

- /b/:board => /b/BOARD NAME or /b/BOARD MONGO ID 
example usage: Our original crossword at: https://worrd.herokuapp.com/b/58a23242619c5300118857bc or https://worrd.herokuapp.com/b/Original%20Board

Grabs the board from the database and deploy it ready to solve. When solved, the client sends a POST to the server at /s/. The POST contains recalculated solve count, recalculate average solve time, user ID, and solution metadata. Upon receiving the data, the server

- /mine => list all of my boards (only accessible when logged in)

- /meta => list all of my solve information (only accessible when logged in)

### Authentication
Uses Passport LocalStrategy. http://passportjs.org/

- /login => self-explanatory, uses Passport LocalStrategy to log in. Can expand Login and Register to use other strategies like Oauth so you can log in with Twitter, Google+, Facebook account, whatever you like really! Passport is pretty easy.

- /register => same as above

- /logout => kills session, logs out user

### Back-end
I added three Mongoose data models. All new boards are stored in Board with metadata you wrote from your original JSON object prototype. I store a bit of metadata with the board. For more verbose metadata, I created a Meta collection. This stores information on seconds-per-word as well as an entry for each solve for any given puzzle. We can recall a particular user's solve of a puzzle because the User collection has a key solves which contains an array of ObjectIDs of Meta documents corresponding to that user's solves. You can see these solves when you click "My Solves" or go to the /meta route.

```javascript
let boardSchema = new Schema({
  meta: {
    title: String,
    author: String,
    description: String,
    dateCreated: Date,
    language: { type: String, default: 'en' },
    size: Number,
    stats: {
      totalSolves: Number,
      averageSolveTime: Number,
      userRatedQuality: Array,
      userRatedDifficulty: Array
    }
  },
  data: [{}]
});
```

```javascript
let metaSchema = new Schema({
  boardID: {type: mongoose.Schema.Types.ObjectId, ref: 'Board'},
  dateSolved: { type: Date, default: Date.now },
  user: String,
  solveData: String
});
```

```javascript
let userSchema = new Schema({
    username: String,
    password: String,
    solves: [{type:Schema.Types.ObjectId, ref: 'Meta'}]
 });
```
## Things that don't work well at all yet
- [  ] Add new board: there's no bounds checking if your 1A 2A 3A etc., fits within the size of the board, so you can write outside the bounds of the board. If you write inside the bounds of the board, it wraps. Also, the textarea interface is atrocious, but it DOES work for quick tests of the data model and stuff. Down the road this would be where we have a really nice UI for editing/board design
- [  ] Meta should include board title so you can view boards by name on the "My Solves" page
- [  ] Maybe Meta should not even be its own data model and should be merged with Board and save User solves directly to the User document.

- [  ] Things to add: Nicer output of clues / board so we can save to pdf or make printer friendly. Should be NPM module for this
- [  ] Error handling
- [  ] Server monitoring
- [  ] Better use of promises / mongoose query syntax
- [  ] Think about using React or another view framework as development progresses.

## Other stuff to think about?

- What sort of data would we like to store / stats would we like to display and so forth?
- What kind of UI do we want for the "guide the user to design a crossword" thing?
- Are we happy with using the 1A 1C etc., reference for the row-col cords of our grid?

### CODE REVIEW

**Comment by thmsdnnr** [comment]
potential random idea:
-social network-y angle with following/followers: you can friend other users and see their recent solves, "challenge" them on a puzzle they've recently solved, etc. get points or something for winning challenges? maybe some sort of level system or gamification

algorithm thoughts:
I think the really huge thing will be making a nice interface for editing and designing puzzles. I'm reading up a lot on how to go about doing it. It sounds like we'll want to store a dictionary of words in a trie 
https://www.topcoder.com/community/data-science/data-science-tutorials/using-tries/ https://www.cs.bu.edu/teaching/c/tree/trie/

Maybe step #1: nice UI for user to create a new board. select a size and then have a way for them to enter words entirely manually, enter clues, have the board saved, and then let it be solvable on the site.

step #2: figure out "autocomplete" for a given word by suggesting words that could fit in a certain spot given existing words. this way we only have to check the single word and the surrounding words, so it won't matter if our algorithm is painfully slow.

In my head it's something like, imagine you're entering a word in where the ?? are below.

C-A-R-?
--------?
--------?
C-A-R-E

Maybe assume we give the algorithm a desired word length, too (in addition to the obvious bounds, like a word can't extend off the board). In this case, 4. The algorithm's like okay, the word starts at the end of CAR, so what words in the dictionary are 4 letters that start with CAR. Okay, find this list. Then, how many of those 4 letter words end with E? If words such as this exist, suggest them.

I imagine the bounds-checking to work similarly with more words. It's just like, start at one constraint, find all words that satisfy it, create a list. Then from that list, find all words that satisfy the second constraint. So we just continually filter a list to solve all the constraints (first, the maximum length and the exact length, if supplied, and then real words in every direction) and then display the possibilities.

We could save the lists as we filter (since this is partially user-input). For instance, if there are no words that fit EXACTLY, save a list of words that fit except for one or two constraints (maybe they make one or two other existing words no longer words) and display the suggestion but with the culprit letters somehow called out. So like "If you like this word better, you can add it, but then you'll need to change these words it conflicts with."

Maybe we could even be smart about conflicts: e.g., some conflicts are not as bad as others, especially singular->plural, plural->singular. So CARS could become CAR+BLACK CELL or vice versa. Perhaps the rebus thing could come into play somewhere here too. I dunno! Exciting and very complex and fun I think :neckbeard:

**Comment by kbrtrm** [comment]
! 😲 Dude, I'm floored by this.

**Comment by kbrtrm** [comment]
Another idea as I'm reading this:
Comments on board available after solve

Totally with you on the importance of the interface. Does it seem like board pattern (of black cells) should be dictated by the word arrangement dictated by the algorithm? Or the other way around? Or a combo of both? That seems to be what you're describing—definitely a very complex fun problem to solve. Can't forget that we need to maintain symmetry, too!

Tries tries all the way. That makes a lot of sense. Imagining all the branches of our huge possible word trie. :drooling_face:

**Comment by thmsdnnr** [comment]
🎉  Redeployed with updated style. 🎉

Log in as test/test again and check out https://worrd.herokuapp.com/new for the new board creation UI. Much much nicer. And still we can improve it way more.

I added jquery-min to the project so we're not pulling it in from a CDN. I made one small change to index.js Kevin, setting the keydown listener to the board div only (so it didn't interfere with the clue entering code when I append those inputs to the page). It changes this:
`$(window).keydown(function(e) {` to this `$('div#board').keydown(function(e) {`

## The major change here is that I implemented some code to parse the boards that the user enters into words, horizontal and vertical. 

Basically it's code that does the reverse of what the original code did: that code translated a given JSON object to a board, and this code translates user-entered words into a JSON object. It's kind of gnarly but OMG it works. The strategy is basically this (the up, down, left, right functions are just bounds-checking functions so we don't try to access outside the array and can help figure out if you're at the top/left/bottom/right of the board in the for loops):

Go through the user-entered array row-by-row left-to-right, starting at the top. When you encounter the first non-blank character (in this case, a tilde which is what we map a black square to), look to the right. If there's a character there, then **this bakes in the assumption that words must be a minimum of two characters** this is a horizontal word. Save the current cell as the START of the word (we translate the x,y index to a NUMBER-LETTER code, like 1A). Continue incrementing one by one to the right until we reach the end of the board or a tilde. When we do, log this as a word, tie it to the number-letter code. Also, for each letter we log, populate the dictionary alreadyUsed. alreadyUsed maps indices to a V or H so that we can check to see if we've already saved this word. If we didn't do this, the code would log three words for the horizontal word "TREE" say: it would first get "TREE", then it would get "REE", then it would get "EE", and then E+~ would not be recorded. I decided to use this alreadyUsed dictionary instead of fiddling with the for loop variables directly.

After we've run through the array horizontally, we run through it vertically. At first I had both operations in the same for loop, and I think this is faster, but honestly it was so unreadable I don't think it's worth it. 

The vertical strategy is similar. Go through the array row by row, but this time when you reach a non-blank cell, look up. If the cell above is either blank or the top of the board, then we're potentially at the start of a vertical word. Look down. If the cell below has a letter, then we are at the start of a vertical word. Log the current cell as the start of the word, and add letters to the word, going down, until we reach another either blank character or bottom of the board. 

Once we get all the keys, we iterate over the keys and create inputs for each of the keys (since each is now a word in need of a clue). These inputs pop into a form at the bottom of the page, and I did a JS form handling to prevent default submission since I couldn't get it to work without this. I grab all the user-submitted clues (the clues default to simply the word itself if none is provided) and send them to the server. The server saves the JSON object, sends back a response, and if the response is Status-Code 200, the browser redirects to the saved board!

```javascript
function generateTheDictionary(testArr) {
    let currentWordCode;
    let currentWord=[];
    let wordDirection;

    //call with i to determine whether we can access this index
    let up=canLookUp(testArr.length);
    let down=canLookDown(testArr.length);
    //call with j to determine whether we can access this index
    let left=canLookLeft(testArr.length);
    let right=canLookRight(testArr.length);

  let alreadyUsed={}; //alreadyUsed maps an [row, col] to a V or an H.
  //if V, index has already been used in a Vertical word
  //if H, index has already been used in a Horizontal word

  //find horizontal words and log them
  for (var i=0;i<testArr.length;i++) {
    for (var j=0;j<testArr[i].length;j++) {
      if (!isCellEmpty(testArr[i][j])&&!alreadyUsed[`${i},${j}`]) {
        currentWord=[];
        if ((right(j)&&!isCellEmpty(testArr[i][j+1]))) {
          //the cell to the right is empty and we're not at the right side of the board
          currentWordCode=indexToLetNum(i,j);
          let ct=j;
          currentWord.push(testArr[i][ct]);
          alreadyUsed[`${i},${ct}`]=wordDirection;
          wordDirection='H';
          let go=true;
          while (go&&right(ct)) { //go to the right storing letters
            ct++;
            if(!isCellEmpty(testArr[i][ct])) {
              currentWord.push(testArr[i][ct]);
              alreadyUsed[`${i},${ct}`]=wordDirection;
              }
              else {
                go=false;
              }
            }
            currentWord=currentWord.join("");
            dictionize(currentWordCode, currentWord, wordDirection);
          }
        }
        else { //the cell is empty.
          continue;
          }
        }
      }

  alreadyUsed={}; //alreadyUsed maps an [row, col] to a V or an H.
  //find vertical words and log them
  for (var i=0;i<testArr.length;i++) {
    for (var j=0;j<testArr[i].length;j++) {
      if (!isCellEmpty(testArr[i][j])&&!alreadyUsed[`${i},${j}`]) {
        currentWord=[];
        if ((up(i)&&isCellEmpty(testArr[i-1][j]))||(!up(i))) { //the cell above us is empty or we're at the top of the board
          //we are at the top of a word, so test if it's vertical or horizontal
          currentWordCode=indexToLetNum(i,j);
          if (down(i)&&!isCellEmpty(testArr[i+1][j])) { //the cell below us is NOT empty, the word is vertical
            let ct=i;
            currentWord.push(testArr[ct][j]);
            wordDirection='V';
            alreadyUsed[`${ct},${j}`]=wordDirection;
            let go=true;
            while (down(ct)&&go) { //go down to the bottom storing letters
              ct++;
              if (!isCellEmpty(testArr[ct][j])) {
                currentWord.push(testArr[ct][j]);
                alreadyUsed[`${ct},${j}`]=wordDirection;
              }
              else {go=false;}
            }
            currentWord=currentWord.join("");
            dictionize(currentWordCode, currentWord, wordDirection);
          }
        }
      }
    }
  }
  return alreadyUsed;
  }
//helper functions
function indexToLetNum(row, col) { //gives letter-number code given a row, col index in a 2D array
    let code,letter,number;
    number=row+1;
    letter=String.fromCharCode(col+65); //if col=0, letter is A
    code = `${number}${letter}`
    return code;
  }

  function isCellEmpty(cell) {
    return (cell==='~'||cell==='');
  }

  function canLookUp(length) {
    return function(i) {
      return (i>0);
    }
  }
  function canLookDown(length) {
    return function(i) {
      return (i<length-1);
    }
  }
  function canLookLeft(length) {
    return function(j) {
      return (j>0);
    }
  }
  function canLookRight(length) {
    return function(j) {
      return (j<length-1);
    }
  }

  function dictionize(code, word, direction, clue) {
    console.log('code,word,direction,clue', code,word,direction,clue);
    clue=clue||`${word}`;
    wordPosDict[`${code}-${direction}`] = {word:word,clue:clue,dir:direction};
  }
```
## other updates
You can now see the Titles of boards on the "MY SOLVES" page. The test/test user still exists, but I got rid of the tab delimited format since the input was terrible. Now just using pure JSON objects. Still to-do:
[   ] Make sure you can't submit an empty board (or a board with only black squares)
[   ] Start figuring out how to suggest words / update the UI for this...not sure how it will look yet
[   ] Update UI for existing board generator, as it's a little hacky, especially the way the clues just magically appear in a little scrollable div at the bottom
[   ] Restore the tab-delimited-value import. Could import tab-delimited, comma delimited, other common formats

# Stuff to talk to you about tomorrow! 
One other idea I had for it we could talk about tomorrow: sort of "scrolling inertia" in the input mode.
- Usually when you enter a character it makes sense to go left-to-right. But what if you're entering vertical characters? You have to keep going left-down or down-left.
- Create a listener for the last two keypresses. If it's left-down or down-left, change the default text entry direction to vertical.
- While it's vertical, listen for an up-right keypress or a right-up keypress combo. This indicates the user is trying to go back to left-to-right. Swap the text direction back to horizontal.

It might not make sense for crossword puzzle entry itself (or might not even make sense at all!) but it might be nice usability enhancement for puzzle entry. 

Remind me too to ask you about how to update your script on board-size change. Currently the size plays fine when I change the class on page reload, but when I try to update it without a reload, I can't get things to redraw because I don't know what function to call. I played with it a little but just broke everything so you can help me :)

**Comment by thmsdnnr** [comment]
Also I'm not good at replying to comments on here / have no idea how it works@! The board structure as dictated by the algorithm + symmetry is definitely something to look into. So far the algorithm does not even exist! I was planning to do something like I just did with better board creation UI, then slowly implement the algorithm as like "autocomplete" on words that are missing a few letters, and then go from there. I feel getting the words in + autocomplete is easy step, step one maybe. In that case, the constraints on the search are applied by the user (it's already X letters long, it's missing Y letters, and the intervening string(s) is/are Z). From there figure out how to layout stuff maybe? So instead of user entering a word, we pick some random word with some parameters and it generates its own constraints on the next word and we can go from there?

It's an interesting idea too: do we generate some boards that have set black blocks on them and have these constraints baked in, or do we let the algorithm generate black blocks in cases where it finds no matches for a given set of constraints / exceeds some set time we give it for finding a word?

**Comment by thmsdnnr** [comment]
ENABLE word list

**Comment by thmsdnnr** [comment]
-useful links-
epic word list: https://github.com/bgreenlee/scrabble-suggest/tree/master/data/word_list_moby_crossword-flat

http://stackoverflow.com/questions/1953080/good-algorithm-and-data-structure-for-looking-up-words-with-missing-letters
https://www.reddit.com/r/compsci/comments/1856zv/what_is_the_fastest_datastructure_for_crossword
http://stackoverflow.com/questions/2288901/best-data-structure-for-crossword-puzzle-search
http://nlp.stanford.edu/IR-book/html/htmledition/wildcard-queries-1.html
https://en.wikipedia.org/wiki/Trie
https://gist.github.com/DataWraith/262667
https://en.wikipedia.org/wiki/Suffix_array
https://en.wikipedia.org/wiki/Suffix_tree

https://codecanyon.net/item/crossword-generator/14375662
https://www.cs.rpi.edu/~dhulena/CS44FinalProjectReport.pdf

https://github.com/rschroll/crosswords

**Comment by thmsdnnr** [comment]
Redeployed with the ENABLE word list (172,820 words, hence the massive line of code addage on the PR...heh, not sure how to make GH ignore that) and some basic autopopulation features.
This set of constraints  can autopopulate like this: . 

Not perfect but a start! 

Also included a word solver utility https://worrd.herokuapp.com/solve (enter letters with a * for wildcard and get all the words in the ENABLE dictionary).

To play around with the computer generated, it's https://worrd.herokuapp.com/c/NUMERICSIZEOFBOARD, or you can go to https://worrd.herokuapp.com/n and click one of the links in the lower pane.

**Comment by kbrtrm** [comment]
Holy MOLY. Yes!

**Pull request merged**
