### PR TITLE
Fix for Issue #8

### PR DESCRIPTION
**Pull request by thmsdnnr**
This should fix issue #8. In the process I found that the array indexing I'm using is a little wonky, calling rows cols and cols rows, which **works**, but I'll go back and clean that up tomorrow.

Also, I didn't push it to Heroku yet as it's a breaking change and I haven't written the transform. I'll add that to a PR tomorrow with the indexing cleanup.

### CODE REVIEW

**Comment by thmsdnnr** [comment]
# :flags: celebratory carp streamer
This fix is now complete for real. I wrote a step-up and step-down transform for the data. I ran it remotely on the database and deployed the fix to Heroku. All the old boards work now, as well as newly-created ones, as you'd expect.

===

I used https://github.com/afloyd/mongo-migrate (SUPER SUPER SIMPLE!)
To run the fix on your local database:

1) **npm install** (or install manually with **npm install mongo-migrate**).
2) **node ./node_modules/mongodb-migrate -runmm -dbc '{ "host":"localhost","db":"xword"}' up**
^ the above assumes you have no password for your db and haven't configured security. If you have you can check out the mongo-migrate link for more advanced syntax or even making a json config file rather than inlining the configuration.

Change up to down if you want to reverse the migrations. If we have multiple migrations in the migrations folder, you can number them sequentially and then specify what to transform down "to". Leaving it blank and writing just down transforms all the way down.

Glad I went through this process...was a tiny pain but so much easier than expected & I'm now 100% less hesitent to write changes to a data model that changes existing data. This Soverflow (http://stackoverflow.com/a/22444820/7316502) is very helpful detailing how you can tie versioning to schema (as well as the version for a GIVEN USER and run transforms on the fly for the data that user accesses) but hopefully things will never get that skewed haha

**Comment by thmsdnnr** [comment]
I thought there was a small bug with mongo-migrate, but I think it was bad transform code. Now transforms work both ways. HUZZAH><

**Comment by kbrtrm** [comment]
🎏 🐟

**Comment by kbrtrm** [comment]
AWESOME.

**Pull request merged**
